export const tagline: string[] = [
    "TRANSFORM YOUR EMAILS, UNLOCK OPPORTUNITIES",
    "TRANSFORM YOUR EMAILS, SEIZE NEW POSSIBILITIES",
    "TRANSFORM YOUR EMAILS, OPEN DOORS TO SUCCESS",
    "TRANSFORM YOUR EMAILS, CAPTURE THE ATTENTION YOU DESERVE"
]