version: "3.8"

services:
  backend:
    build: ./mailify-back
    container_name: backend
    ports:
      - "5000:5000" 
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
    networks:
      - app-network

  frontend:
    build: ./mailify-front
    container_name: frontend
    ports:
      - "80:80" 
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
